# Generated by Django 4.2.1 on 2023-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_image_path_alter_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
