# Generated by Django 4.2.1 on 2023-06-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_path',
        ),
    ]
